import { Exercise } from '@/types';

export const MUSCLE_GROUPS = [
  { id: 'abs', name: 'Abs', percentage: 100 },
  { id: 'back', name: 'Back', percentage: 100 },
  { id: 'biceps', name: 'Biceps', percentage: 100 },
  { id: 'chest', name: 'Chest', percentage: 100 },
  { id: 'glutes', name: 'Glutes', percentage: 100 },
  { id: 'hamstrings', name: 'Hamstrings', percentage: 100 },
  { id: 'quadriceps', name: 'Quadriceps', percentage: 100 },
  { id: 'shoulders', name: 'Shoulders', percentage: 100 },
  { id: 'triceps', name: 'Triceps', percentage: 100 },
] as const;

export const EXERCISE_CATEGORIES = [
  { id: 'chest', name: 'Chest', emoji: '💪' },
  { id: 'back', name: 'Back', emoji: '🏋️' },
  { id: 'shoulders', name: 'Shoulders', emoji: '🤸' },
  { id: 'arms', name: 'Arms', emoji: '💪' },
  { id: 'legs', name: 'Legs', emoji: '🦵' },
  { id: 'core', name: 'Core', emoji: '🔥' },
  { id: 'cardio', name: 'Cardio', emoji: '❤️' },
  { id: 'full-body', name: 'Full Body', emoji: '🏃' },
] as const;

export const DEFAULT_EXERCISES: Exercise[] = [
  // CHEST EXERCISES
  {
    id: '1',
    name: 'Bench Press',
    category: 'chest',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: 'Barbell',
  },
  {
    id: '2',
    name: 'Incline Bench Press',
    category: 'chest',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    equipment: 'Barbell',
  },
  {
    id: '3',
    name: 'Decline Bench Press',
    category: 'chest',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: 'Barbell',
  },
  {
    id: '4',
    name: 'Dumbbell Bench Press',
    category: 'chest',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: 'Dumbbells',
  },
  {
    id: '5',
    name: 'Incline Dumbbell Press',
    category: 'chest',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    equipment: 'Dumbbells',
  },
  {
    id: '6',
    name: 'Decline Dumbbell Press',
    category: 'chest',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: 'Dumbbells',
  },
  {
    id: '7',
    name: 'Dumbbell Flyes',
    category: 'chest',
    muscleGroups: ['chest'],
    equipment: 'Dumbbells',
  },
  {
    id: '8',
    name: 'Incline Dumbbell Flyes',
    category: 'chest',
    muscleGroups: ['chest'],
    equipment: 'Dumbbells',
  },
  {
    id: '9',
    name: 'Cable Flyes',
    category: 'chest',
    muscleGroups: ['chest'],
    equipment: 'Cable',
  },
  {
    id: '10',
    name: 'Chest Dips',
    category: 'chest',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: 'Bodyweight',
  },
  {
    id: '11',
    name: 'Push-ups',
    category: 'chest',
    muscleGroups: ['chest', 'triceps', 'core'],
    equipment: 'Bodyweight',
  },
  {
    id: '12',
    name: 'Incline Push-ups',
    category: 'chest',
    muscleGroups: ['chest', 'triceps', 'core'],
    equipment: 'Bodyweight',
  },
  {
    id: '13',
    name: 'Decline Push-ups',
    category: 'chest',
    muscleGroups: ['chest', 'triceps', 'core'],
    equipment: 'Bodyweight',
  },
  {
    id: '14',
    name: 'Diamond Push-ups',
    category: 'chest',
    muscleGroups: ['chest', 'triceps'],
    equipment: 'Bodyweight',
  },
  {
    id: '15',
    name: 'Pec Deck Machine',
    category: 'chest',
    muscleGroups: ['chest'],
    equipment: 'Machine',
  },
  {
    id: '16',
    name: 'Chest Press Machine',
    category: 'chest',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipment: 'Machine',
  },

  // BACK EXERCISES
  {
    id: '17',
    name: 'Deadlift',
    category: 'back',
    muscleGroups: ['back', 'glutes', 'hamstrings', 'traps'],
    equipment: 'Barbell',
  },
  {
    id: '18',
    name: 'Sumo Deadlift',
    category: 'back',
    muscleGroups: ['back', 'glutes', 'hamstrings', 'traps'],
    equipment: 'Barbell',
  },
  {
    id: '19',
    name: 'Romanian Deadlift',
    category: 'back',
    muscleGroups: ['back', 'glutes', 'hamstrings'],
    equipment: 'Barbell',
  },
  {
    id: '20',
    name: 'Pull-ups',
    category: 'back',
    muscleGroups: ['back', 'biceps'],
    equipment: 'Pull-up Bar',
  },
  {
    id: '21',
    name: 'Chin-ups',
    category: 'back',
    muscleGroups: ['back', 'biceps'],
    equipment: 'Pull-up Bar',
  },
  {
    id: '22',
    name: 'Wide Grip Pull-ups',
    category: 'back',
    muscleGroups: ['back', 'biceps'],
    equipment: 'Pull-up Bar',
  },
  {
    id: '23',
    name: 'Lat Pulldown',
    category: 'back',
    muscleGroups: ['back', 'biceps'],
    equipment: 'Cable',
  },
  {
    id: '24',
    name: 'Wide Grip Lat Pulldown',
    category: 'back',
    muscleGroups: ['back', 'biceps'],
    equipment: 'Cable',
  },
  {
    id: '25',
    name: 'Bent-over Barbell Row',
    category: 'back',
    muscleGroups: ['back', 'biceps', 'rear delts'],
    equipment: 'Barbell',
  },
  {
    id: '26',
    name: 'Bent-over Dumbbell Row',
    category: 'back',
    muscleGroups: ['back', 'biceps', 'rear delts'],
    equipment: 'Dumbbells',
  },
  {
    id: '27',
    name: 'Single Arm Dumbbell Row',
    category: 'back',
    muscleGroups: ['back', 'biceps'],
    equipment: 'Dumbbells',
  },
  {
    id: '28',
    name: 'T-Bar Row',
    category: 'back',
    muscleGroups: ['back', 'biceps', 'rear delts'],
    equipment: 'T-Bar',
  },
  {
    id: '29',
    name: 'Cable Row',
    category: 'back',
    muscleGroups: ['back', 'biceps', 'rear delts'],
    equipment: 'Cable',
  },
  {
    id: '30',
    name: 'Face Pulls',
    category: 'back',
    muscleGroups: ['rear delts', 'traps', 'rhomboids'],
    equipment: 'Cable',
  },
  {
    id: '31',
    name: 'Reverse Flyes',
    category: 'back',
    muscleGroups: ['rear delts', 'rhomboids'],
    equipment: 'Dumbbells',
  },
  {
    id: '32',
    name: 'Shrugs',
    category: 'back',
    muscleGroups: ['traps'],
    equipment: 'Dumbbells',
  },
  {
    id: '33',
    name: 'Barbell Shrugs',
    category: 'back',
    muscleGroups: ['traps'],
    equipment: 'Barbell',
  },

  // SHOULDER EXERCISES
  {
    id: '34',
    name: 'Overhead Press',
    category: 'shoulders',
    muscleGroups: ['shoulders', 'triceps', 'core'],
    equipment: 'Barbell',
  },
  {
    id: '35',
    name: 'Dumbbell Shoulder Press',
    category: 'shoulders',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'Dumbbells',
  },
  {
    id: '36',
    name: 'Seated Dumbbell Press',
    category: 'shoulders',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'Dumbbells',
  },
  {
    id: '37',
    name: 'Arnold Press',
    category: 'shoulders',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'Dumbbells',
  },
  {
    id: '38',
    name: 'Lateral Raises',
    category: 'shoulders',
    muscleGroups: ['shoulders'],
    equipment: 'Dumbbells',
  },
  {
    id: '39',
    name: 'Front Raises',
    category: 'shoulders',
    muscleGroups: ['shoulders'],
    equipment: 'Dumbbells',
  },
  {
    id: '40',
    name: 'Rear Delt Flyes',
    category: 'shoulders',
    muscleGroups: ['rear delts'],
    equipment: 'Dumbbells',
  },
  {
    id: '41',
    name: 'Cable Lateral Raises',
    category: 'shoulders',
    muscleGroups: ['shoulders'],
    equipment: 'Cable',
  },
  {
    id: '42',
    name: 'Upright Rows',
    category: 'shoulders',
    muscleGroups: ['shoulders', 'traps'],
    equipment: 'Barbell',
  },
  {
    id: '43',
    name: 'Pike Push-ups',
    category: 'shoulders',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: 'Bodyweight',
  },
  {
    id: '44',
    name: 'Handstand Push-ups',
    category: 'shoulders',
    muscleGroups: ['shoulders', 'triceps', 'core'],
    equipment: 'Bodyweight',
  },

  // ARM EXERCISES
  {
    id: '45',
    name: 'Barbell Curls',
    category: 'arms',
    muscleGroups: ['biceps'],
    equipment: 'Barbell',
  },
  {
    id: '46',
    name: 'Dumbbell Curls',
    category: 'arms',
    muscleGroups: ['biceps'],
    equipment: 'Dumbbells',
  },
  {
    id: '47',
    name: 'Hammer Curls',
    category: 'arms',
    muscleGroups: ['biceps', 'forearms'],
    equipment: 'Dumbbells',
  },
  {
    id: '48',
    name: 'Preacher Curls',
    category: 'arms',
    muscleGroups: ['biceps'],
    equipment: 'Barbell',
  },
  {
    id: '49',
    name: 'Cable Curls',
    category: 'arms',
    muscleGroups: ['biceps'],
    equipment: 'Cable',
  },
  {
    id: '50',
    name: 'Concentration Curls',
    category: 'arms',
    muscleGroups: ['biceps'],
    equipment: 'Dumbbells',
  },
  {
    id: '51',
    name: 'Close Grip Bench Press',
    category: 'arms',
    muscleGroups: ['triceps', 'chest'],
    equipment: 'Barbell',
  },
  {
    id: '52',
    name: 'Tricep Dips',
    category: 'arms',
    muscleGroups: ['triceps', 'chest'],
    equipment: 'Bodyweight',
  },
  {
    id: '53',
    name: 'Overhead Tricep Extension',
    category: 'arms',
    muscleGroups: ['triceps'],
    equipment: 'Dumbbells',
  },
  {
    id: '54',
    name: 'Tricep Pushdowns',
    category: 'arms',
    muscleGroups: ['triceps'],
    equipment: 'Cable',
  },
  {
    id: '55',
    name: 'Skull Crushers',
    category: 'arms',
    muscleGroups: ['triceps'],
    equipment: 'Barbell',
  },
  {
    id: '56',
    name: 'Diamond Push-ups',
    category: 'arms',
    muscleGroups: ['triceps', 'chest'],
    equipment: 'Bodyweight',
  },
  {
    id: '57',
    name: 'Wrist Curls',
    category: 'arms',
    muscleGroups: ['forearms'],
    equipment: 'Dumbbells',
  },
  {
    id: '58',
    name: 'Reverse Wrist Curls',
    category: 'arms',
    muscleGroups: ['forearms'],
    equipment: 'Dumbbells',
  },

  // LEG EXERCISES
  {
    id: '59',
    name: 'Back Squat',
    category: 'legs',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: 'Barbell',
  },
  {
    id: '60',
    name: 'Front Squat',
    category: 'legs',
    muscleGroups: ['quadriceps', 'glutes', 'core'],
    equipment: 'Barbell',
  },
  {
    id: '61',
    name: 'Goblet Squat',
    category: 'legs',
    muscleGroups: ['quadriceps', 'glutes'],
    equipment: 'Dumbbells',
  },
  {
    id: '62',
    name: 'Bulgarian Split Squat',
    category: 'legs',
    muscleGroups: ['quadriceps', 'glutes'],
    equipment: 'Bodyweight',
  },
  {
    id: '63',
    name: 'Leg Press',
    category: 'legs',
    muscleGroups: ['quadriceps', 'glutes'],
    equipment: 'Machine',
  },
  {
    id: '64',
    name: 'Leg Extension',
    category: 'legs',
    muscleGroups: ['quadriceps'],
    equipment: 'Machine',
  },
  {
    id: '65',
    name: 'Leg Curls',
    category: 'legs',
    muscleGroups: ['hamstrings'],
    equipment: 'Machine',
  },
  {
    id: '66',
    name: 'Romanian Deadlift',
    category: 'legs',
    muscleGroups: ['hamstrings', 'glutes'],
    equipment: 'Barbell',
  },
  {
    id: '67',
    name: 'Stiff Leg Deadlift',
    category: 'legs',
    muscleGroups: ['hamstrings', 'glutes'],
    equipment: 'Barbell',
  },
  {
    id: '68',
    name: 'Walking Lunges',
    category: 'legs',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: 'Bodyweight',
  },
  {
    id: '69',
    name: 'Reverse Lunges',
    category: 'legs',
    muscleGroups: ['quadriceps', 'glutes'],
    equipment: 'Bodyweight',
  },
  {
    id: '70',
    name: 'Side Lunges',
    category: 'legs',
    muscleGroups: ['quadriceps', 'glutes', 'adductors'],
    equipment: 'Bodyweight',
  },
  {
    id: '71',
    name: 'Hip Thrusts',
    category: 'legs',
    muscleGroups: ['glutes', 'hamstrings'],
    equipment: 'Barbell',
  },
  {
    id: '72',
    name: 'Glute Bridges',
    category: 'legs',
    muscleGroups: ['glutes', 'hamstrings'],
    equipment: 'Bodyweight',
  },
  {
    id: '73',
    name: 'Calf Raises',
    category: 'legs',
    muscleGroups: ['calves'],
    equipment: 'Bodyweight',
  },
  {
    id: '74',
    name: 'Seated Calf Raises',
    category: 'legs',
    muscleGroups: ['calves'],
    equipment: 'Machine',
  },
  {
    id: '75',
    name: 'Jump Squats',
    category: 'legs',
    muscleGroups: ['quadriceps', 'glutes', 'calves'],
    equipment: 'Bodyweight',
  },
  {
    id: '76',
    name: 'Single Leg Deadlift',
    category: 'legs',
    muscleGroups: ['hamstrings', 'glutes', 'core'],
    equipment: 'Dumbbells',
  },
  {
    id: '77',
    name: 'Step-ups',
    category: 'legs',
    muscleGroups: ['quadriceps', 'glutes'],
    equipment: 'Bodyweight',
  },

  // CORE EXERCISES
  {
    id: '78',
    name: 'Plank',
    category: 'core',
    muscleGroups: ['core', 'shoulders'],
    equipment: 'Bodyweight',
  },
  {
    id: '79',
    name: 'Side Plank',
    category: 'core',
    muscleGroups: ['core', 'obliques'],
    equipment: 'Bodyweight',
  },
  {
    id: '80',
    name: 'Crunches',
    category: 'core',
    muscleGroups: ['core'],
    equipment: 'Bodyweight',
  },
  {
    id: '81',
    name: 'Bicycle Crunches',
    category: 'core',
    muscleGroups: ['core', 'obliques'],
    equipment: 'Bodyweight',
  },
  {
    id: '82',
    name: 'Russian Twists',
    category: 'core',
    muscleGroups: ['core', 'obliques'],
    equipment: 'Bodyweight',
  },
  {
    id: '83',
    name: 'Mountain Climbers',
    category: 'core',
    muscleGroups: ['core', 'shoulders'],
    equipment: 'Bodyweight',
  },
  {
    id: '84',
    name: 'Dead Bug',
    category: 'core',
    muscleGroups: ['core'],
    equipment: 'Bodyweight',
  },
  {
    id: '85',
    name: 'Leg Raises',
    category: 'core',
    muscleGroups: ['core'],
    equipment: 'Bodyweight',
  },
  {
    id: '86',
    name: 'Hanging Leg Raises',
    category: 'core',
    muscleGroups: ['core'],
    equipment: 'Pull-up Bar',
  },
  {
    id: '87',
    name: 'Ab Wheel Rollout',
    category: 'core',
    muscleGroups: ['core', 'shoulders'],
    equipment: 'Ab Wheel',
  },
  {
    id: '88',
    name: 'Cable Crunches',
    category: 'core',
    muscleGroups: ['core'],
    equipment: 'Cable',
  },
  {
    id: '89',
    name: 'Wood Chops',
    category: 'core',
    muscleGroups: ['core', 'obliques'],
    equipment: 'Cable',
  },
  {
    id: '90',
    name: 'Hollow Body Hold',
    category: 'core',
    muscleGroups: ['core'],
    equipment: 'Bodyweight',
  },

  // CARDIO EXERCISES
  {
    id: '91',
    name: 'Treadmill Running',
    category: 'cardio',
    muscleGroups: ['legs', 'cardiovascular'],
    equipment: 'Treadmill',
  },
  {
    id: '92',
    name: 'Stationary Bike',
    category: 'cardio',
    muscleGroups: ['legs', 'cardiovascular'],
    equipment: 'Bike',
  },
  {
    id: '93',
    name: 'Elliptical',
    category: 'cardio',
    muscleGroups: ['full body', 'cardiovascular'],
    equipment: 'Elliptical',
  },
  {
    id: '94',
    name: 'Rowing Machine',
    category: 'cardio',
    muscleGroups: ['back', 'legs', 'cardiovascular'],
    equipment: 'Rowing Machine',
  },
  {
    id: '95',
    name: 'Burpees',
    category: 'cardio',
    muscleGroups: ['full body', 'cardiovascular'],
    equipment: 'Bodyweight',
  },
  {
    id: '96',
    name: 'Jumping Jacks',
    category: 'cardio',
    muscleGroups: ['full body', 'cardiovascular'],
    equipment: 'Bodyweight',
  },
  {
    id: '97',
    name: 'High Knees',
    category: 'cardio',
    muscleGroups: ['legs', 'cardiovascular'],
    equipment: 'Bodyweight',
  },
  {
    id: '98',
    name: 'Jump Rope',
    category: 'cardio',
    muscleGroups: ['legs', 'cardiovascular'],
    equipment: 'Jump Rope',
  },
  {
    id: '99',
    name: 'Battle Ropes',
    category: 'cardio',
    muscleGroups: ['arms', 'core', 'cardiovascular'],
    equipment: 'Battle Ropes',
  },
  {
    id: '100',
    name: 'Box Jumps',
    category: 'cardio',
    muscleGroups: ['legs', 'cardiovascular'],
    equipment: 'Plyometric Box',
  },

  // FULL BODY EXERCISES
  {
    id: '101',
    name: 'Thrusters',
    category: 'full-body',
    muscleGroups: ['shoulders', 'legs', 'core'],
    equipment: 'Dumbbells',
  },
  {
    id: '102',
    name: 'Clean and Press',
    category: 'full-body',
    muscleGroups: ['shoulders', 'back', 'legs'],
    equipment: 'Barbell',
  },
  {
    id: '103',
    name: 'Turkish Get-ups',
    category: 'full-body',
    muscleGroups: ['core', 'shoulders', 'legs'],
    equipment: 'Kettlebell',
  },
  {
    id: '104',
    name: 'Kettlebell Swings',
    category: 'full-body',
    muscleGroups: ['glutes', 'hamstrings', 'core'],
    equipment: 'Kettlebell',
  },
  {
    id: '105',
    name: 'Man Makers',
    category: 'full-body',
    muscleGroups: ['full body'],
    equipment: 'Dumbbells',
  },
  {
    id: '106',
    name: 'Bear Crawl',
    category: 'full-body',
    muscleGroups: ['core', 'shoulders', 'legs'],
    equipment: 'Bodyweight',
  },
  {
    id: '107',
    name: 'Farmer\'s Walk',
    category: 'full-body',
    muscleGroups: ['forearms', 'traps', 'core'],
    equipment: 'Dumbbells',
  },
  {
    id: '108',
    name: 'Sled Push',
    category: 'full-body',
    muscleGroups: ['legs', 'core', 'shoulders'],
    equipment: 'Sled',
  },
  {
    id: '109',
    name: 'Sled Pull',
    category: 'full-body',
    muscleGroups: ['back', 'legs', 'core'],
    equipment: 'Sled',
  },
  {
    id: '110',
    name: 'Medicine Ball Slams',
    category: 'full-body',
    muscleGroups: ['core', 'shoulders', 'back'],
    equipment: 'Medicine Ball',
  },
];